### ISSUE TITLE
Make Collection Component cickable

### ISSUE THREAD

**Issue by ManuelRemer** [ManuelRemer/Breadzilla#25]
## Value statement - a requirement, not a solution
As a user I want to click on my saved recipe and get it back

## Acceptance criteria
- [ ] on click switch to recipe site
- [ ] basic information of saved recipe

## Tasks
- [ ] make button a navLink
- [ ] useParams / navLink -> to new page
- [ ] display required data from savedRecipes (actual state of local storage)

## Size
large
