### ISSUE TITLE
NameSave Component

### ISSUE THREAD

**Issue by ManuelRemer** [ManuelRemer/Breadzilla#3]
## Value statement - a requirement, not a solution
As a user I need a quick overview of the ingredients of my freshly created recipe. I want to give it a name. I want to save it for later or start right now.

## Description (Text, Scribble, Wireframe, Design)
<img width="83" alt="Bildschirmfoto 2021-04-26 um 21 09 23" src="https://user-images.githubusercontent.com/79858001/116137322-b0d52100-a6d3-11eb-9792-9bfa4aa9597b.png">

## Acceptance criteria
- [ ] section logo
- [x] p
- [x] Name Input
- [x] list of ingredients
- [x] save button
- [ ] let's bake button

## Tasks
- [ ] elaborate NameSave.js
  - [x] p with set text
  - [x] Input, type: text
  - [x] sub-component: Ingredients.js
    - [x] placeholder text
  - [x] customized standardButton "save"
    - [x] store recipe-Data in local storage
>                     {
>                       name: ""
>                       list of flours: []
>                      }

  - [x] customized standardButton "lets bake"

## Size
(medium)
