### ISSUE TITLE
Basic document and file structure

### ISSUE THREAD

**Issue by ManuelRemer** [ManuelRemer/Breadzilla#5]
## Value statement - a requirement, not a solution
As a user I want my App quickly, so structure your work well!

## Description (Text, Scribble, Wireframe, Design)
Basic document settings, nothing to show

## Acceptance criteria
- [x] install react-router-dom
- [x] adapt index.html
  - [x] link fonts
  - [x] adapt titel
- [x] adapt App.css
  - [x] add box-sizing thing
  - [x] basic grid for first order components
- [x] colors.css
- [x] basic router-dom (without content) + css-files (display: flex, background-color)

## Tasks
- [x] as above

## Size
(medium)
