### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by ManuelRemer** [ManuelRemer/Breadzilla#6]
## Value statement - a requirement, not a solution
As a user
I want to know whats going on after landing on this page/app. I need a short introduction or welcome text,
so that I can move on intuitively

## Description (Text, Scribble, Wireframe, Design)
<img width="192" alt="Bildschirmfoto 2021-04-26 um 16 03 02" src="https://user-images.githubusercontent.com/79858001/116095651-e6184980-a6a8-11eb-93a5-514f368b859e.png">

pay no attention to the burger menu, it'll not be realized (screen shot is outdated)

## Acceptance criteria
- [x] Header / Headline
- [x] Image "crispy bread"
- [x] welcoming text
- [x] navigation buttons

## Tasks
- [x] Landing Page
  - [x] LandingHeader.js 
    - [x] h1
  - [x] LandingContent.js 
    - [x]  img, p
  - [x] LandingNav.js
    - [x] 2x button component
      - [x] define standard Button.js / Button.css
      - [x] import to Header.js 
      - [x] give it props to customize  

## Size
medium
