### ISSUE TITLE
FlourSelection Component

### ISSUE THREAD

**Issue by ManuelRemer** [ManuelRemer/Breadzilla#7]
## Value statement - a requirement, not a solution
As a user I want to be brought here automatically after having clicked the corresponding button at the landing section.
I want to choose from a predefined range of flours by clicking on them. I need a clear signal that a certain flour is chosen. I want to undo decisions by clicking again. I need a clear action to finalize my decissions or to now that the procedure is completed

## Description (Text, Scribble, Wireframe, Design)
<img width="177" alt="Bildschirmfoto 2021-04-26 um 17 19 14" src="https://user-images.githubusercontent.com/79858001/116107704-8bd0b600-a6b3-11eb-968e-2b87d55febc6.png">

## Acceptance criteria
- [ ] section logo
- [x] headline
- [x] six buttons to choose flour
- [x] submit button

## Tasks
- [x] elaborate FlourSelection.js / Flours.css
- [x] subcomponent FlourButtons.js
  - [x] customized standard buttons (hard coded) or define FlourButtons.js
  - [x] shall change look after being clicked (think about state: chosenFlours[])
- [x] submit button (without functionality so far or navLink to FillUpForm)
- [x] ensure that navLink from Header is working

   
## Size
(medium)
